### ISSUE TITLE
Add readme.md

### ISSUE THREAD

**Issue by fulldecent** [jonchui/AirMac#2]
I have "server started" on the Mac, Mac and iPhone are on the same WiFi network but no AirPlay is available on the phone.

Am I missing something. Are there more instructions for me to follow.

**Comment by Ginkgo001** [comment]
I meet the same problem, I can't get the AirPlay button on the iPhone which is iOS 9. 
What is the correct step to run the project?

**Comment by fulldecent** [comment]
Closing, project is dead
